### ISSUE TITLE
cannot serve demo

### ISSUE THREAD

**Issue by Tallyb** [angular/angular-bazel-example#287]
trying to run the demo app, I get the following: 
Serving livereload script from http://localhost:35729/livereload.js?snipver=1
Server listening on http://Tallys-MacBook-Pro.local:5432/

However, the server address is not available, neither is localhost:5432
What am I missing?

**Comment by maktarsis** [comment]
Interesting

Have you caught any error on `5432` ?

Is port available if you try this?
`netstat -vanp tcp | grep 5432`

**Comment by Tallyb** [comment]
After running the app: 

➜  angular-bazel-example git:(master) netstat -vanp tcp | grep 5432
tcp46      0      0  *.5432                 *.*                    LISTEN      131072 131072  84131      0 0x0100 0x00000026
tcp4       0      0  127.0.0.1.5432         *.*                    LISTEN      131072 131072   4645      0 0x0000 0x00000006
tcp6       0      0  ::1.5432               *.*                    LISTEN      131072 131072   4645      0 0x0000 0x00000006
tcp4       0      0  127.0.0.1.5432         127.0.0.1.56790        TIME_WAIT   407890 146988  84153      0 0x2131 0x0000000c
tcp6       0      0  ::1.5432               ::1.56823              TIME_WAIT   407023 146808  84155      0 0x2131 0x0000000c
tcp6       0      0  ::1.5432               ::1.56836              TIME_WAIT   406997 146808  84157      0 0x2131 0x0000000c
It cannot resolve the name of Tally's-MacBook-Pro.local.

**Comment by ewhauser** [comment]
I can confirm the same problem. This works fine when running `yarn serve-prod`

**Comment by manekinekko** [comment]
Hi, our app is being served over http://localhost:8080. Can you try again and let us know?

**Comment by manekinekko** [comment]
I reproduced this on a pixelbook (shell running inside pinguin). I suspect the devserver does not bind to 0.0.0.0

**Comment by alexeagle** [comment]
Hmm, we start the http server here:
https://github.com/bazelbuild/rules_typescript/blob/3a85a90c259e9c49f652142ce439044baad0f24e/devserver/main.go#L118
from what I can tell from the docs, the fact that we use only the `:port` syntax with no hostname/IP ought to mean that it listens on all network interfaces.

Is it simply a matter of DNS? We print `hostname:port` rather than `localhost:port` for a common case of starting a remote devserver over SSH and then clicking the link to open in a local browser. Maybe the URL with localhost rather than the hostname works?

**Comment by alexeagle** [comment]
@manekinekko If you use http://penguin.linux.test:5432/ it works on chromeos.
I think we'll have to sniff the environment to print the right thing

**Comment by alexeagle** [comment]
sent a google3 PR against the ts_devserver to detect chromeos
